export const locationData = {
    divisions: [
      { id: 'Dhaka', name: 'Dhaka' },
      { id: 'Chittagong', name: 'Chittagong' },
      { id: 'Rajshahi', name: 'Rajshahi' },
      { id: 'Khulna', name: 'Khulna' },
      { id: 'Barisal', name: 'Barisal' },
      { id: 'Sylhet', name: 'Sylhet' },
      { id: 'Rangpur', name: 'Rangpur' },
      { id: 'Mymensingh', name: 'Mymensingh' },
    ],
    districts: {
      Dhaka: [
        { id: 'Dhaka', name: 'Dhaka' },
        { id: 'Faridpur', name: 'Faridpur' },
        { id: 'Gazipur', name: 'Gazipur' },
        { id: 'Gopalganj', name: 'Gopalganj' },
        { id: 'Kishoreganj', name: 'Kishoreganj' },
        { id: 'Madaripur', name: 'Madaripur' },
        { id: 'Manikganj', name: 'Manikganj' },
        { id: 'Munshiganj', name: 'Munshiganj' },
        { id: 'Narayanganj', name: 'Narayanganj' },
        { id: 'Narsingdi', name: 'Narsingdi' },
        { id: 'Rajbari', name: 'Rajbari' },
        { id: 'Shariatpur', name: 'Shariatpur' },
        { id: 'Tangail', name: 'Tangail' },
      ],
      Chittagong: [
        { id: 'Bandarban', name: 'Bandarban' },
        { id: 'Brahmanbaria', name: 'Brahmanbaria' },
        { id: 'Chandpur', name: 'Chandpur' },
        { id: 'Chittagong', name: 'Chittagong' },
        { id: 'Comilla', name: 'Comilla' },
        { id: "Cox's Bazar", name: "Cox's Bazar" },
        { id: 'Feni', name: 'Feni' },
        { id: 'Khagrachhari', name: 'Khagrachhari' },
        { id: 'Lakshmipur', name: 'Lakshmipur' },
        { id: 'Noakhali', name: 'Noakhali' },
        { id: 'Rangamati', name: 'Rangamati' },
      ],
      Rajshahi: [
        { id: 'Bogra', name: 'Bogra' },
        { id: 'Joypurhat', name: 'Joypurhat' },
        { id: 'Naogaon', name: 'Naogaon' },
        { id: 'Natore', name: 'Natore' },
        { id: 'Chapainawabganj', name: 'Chapainawabganj' },
        { id: 'Pabna', name: 'Pabna' },
        { id: 'Rajshahi', name: 'Rajshahi' },
        { id: 'Sirajganj', name: 'Sirajganj' },
      ],
      Khulna: [
        { id: 'Bagerhat', name: 'Bagerhat' },
        { id: 'Chuadanga', name: 'Chuadanga' },
        { id: 'Jessore', name: 'Jessore' },
        { id: 'Jhenaidah', name: 'Jhenaidah' },
        { id: 'Khulna', name: 'Khulna' },
        { id: 'Kushtia', name: 'Kushtia' },
        { id: 'Magura', name: 'Magura' },
        { id: 'Meherpur', name: 'Meherpur' },
        { id: 'Narail', name: 'Narail' },
        { id: 'Satkhira', name: 'Satkhira' },
      ],
      Barisal: [
        { id: 'Barguna', name: 'Barguna' },
        { id: 'Barisal', name: 'Barisal' },
        { id: 'Bhola', name: 'Bhola' },
        { id: 'Jhalokati', name: 'Jhalokati' },
        { id: 'Patuakhali', name: 'Patuakhali' },
        { id: 'Pirojpur', name: 'Pirojpur' },
      ],
      Sylhet: [
        { id: 'Habiganj', name: 'Habiganj' },
        { id: 'Moulvibazar', name: 'Moulvibazar' },
        { id: 'Sunamganj', name: 'Sunamganj' },
        { id: 'Sylhet', name: 'Sylhet' },
      ],
      Rangpur: [
        { id: 'Dinajpur', name: 'Dinajpur' },
        { id: 'Gaibandha', name: 'Gaibandha' },
        { id: 'Kurigram', name: 'Kurigram' },
        { id: 'Lalmonirhat', name: 'Lalmonirhat' },
        { id: 'Nilphamari', name: 'Nilphamari' },
        { id: 'Panchagarh', name: 'Panchagarh' },
        { id: 'Rangpur', name: 'Rangpur' },
        { id: 'Thakurgaon', name: 'Thakurgaon' },
      ],
      Mymensingh: [
        { id: 'Jamalpur', name: 'Jamalpur' },
        { id: 'Mymensingh', name: 'Mymensingh' },
        { id: 'Netrokona', name: 'Netrokona' },
        { id: 'Sherpur', name: 'Sherpur' },
      ],
    },
  }