CREATE DATABASE IF NOT EXISTS benign_fashion CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
CREATE USER IF NOT EXISTS 'devuser'@'%' IDENTIFIED BY 'DevPass@123';
GRANT ALL PRIVILEGES ON benign_fashion.* TO 'devuser'@'%';
FLUSH PRIVILEGES;
